version: "3"

services:
    mpgpdb:
        environment:
            - POSTGRES_DB=mpgp
            - POSTGRES_USER=agent4mpgp
            - POSTGRES_PASSWORD=v3ry23C93tp422w0Rd
        image: mpgp129/mpgpdb
        hostname: mpgpdb
        expose:
            - 5432
        ports:
            - 5432:5432
        container_name: mpgpdb
        labels:
            - SERVICE_NAME=mpgpdb
        volumes:
            - postgres:/var/lib/postgresql/data

    mpgpelastickibana:
        image: mpgp129/mpgpelastickibana
        hostname: mpgpelastickibana
        expose:
            - 9200
            - 5601
        ports:
            - 9200:9200
            - 5601:5601
        container_name: mpgpelastickibana
        labels:
            - SERVICE_NAME=mpgpelastickibana

volumes:
    postgres:
# sed -i "s|%$ENV_KEY1%|$ENV_VALUE1|g;s|%$ENV_KEY2%|$ENV_VALUE2|g" appsettings.json
