COMMANDS_TO_RUN+=('echo 1_before_install.sh ...')
# COMMANDS_TO_RUN+=('nvm install lts/*')
# COMMANDS_TO_RUN+=('sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg')
# COMMANDS_TO_RUN+=('echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list')
# COMMANDS_TO_RUN+=('sudo apt-get update -qq')
# COMMANDS_TO_RUN+=('sudo apt-get install -y -qq yarn')