// <auto-generated />
// Copyright (c) MPGP. All rights reserved.
// Licensed under the BSD license. See LICENSE file in the project root for full license information.

using System;
using System.IO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Mpgp.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181126074833_Initial")]
    public class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            const string sqlFile = "../../artifacts/sql/20181126074833_Initial.sql";
            migrationBuilder.Sql(File.ReadAllText(sqlFile));
        }

        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            throw new NotImplementedException();
        }
    }
}
