  
name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          DOCKER_IMAGE_OWNER: mpgp129
          DOCKER_IMAGE_NAME_WEB: mpgpweb
          DOCKER_IMAGE_NAME_PR: mpgpprometheus
          DOCKER_IMAGE_NAME_GR: mpgpgrafana
          DOCKER_IMAGE_NAME_EK: mpgpelastickibana
          DOCKER_IMAGE_NAME_DB: mpgpdb
        run: |
          bash scripts/bash/docker/build.sh mpgpweb
          bash scripts/bash/docker/build.sh mpgpprometheus
          bash scripts/bash/docker/build.sh mpgpgrafana
          bash scripts/bash/docker/build.sh mpgpelastickibana
          bash scripts/bash/docker/build.sh mpgpdb

      - name: Push GH-Packages
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u loktionov129 --password-stdin

          docker tag mpgp129/mpgpweb docker.pkg.github.com/mpgp/mpgp/mpgpweb
          docker push docker.pkg.github.com/mpgp/mpgp/mpgpweb

          docker tag mpgp129/mpgpprometheus docker.pkg.github.com/mpgp/mpgp/mpgpprometheus
          docker push docker.pkg.github.com/mpgp/mpgp/mpgpprometheus

          docker tag mpgp129/mpgpgrafana docker.pkg.github.com/mpgp/mpgp/mpgpgrafana
          docker push docker.pkg.github.com/mpgp/mpgp/mpgpgrafana

          docker tag mpgp129/mpgpelastickibana docker.pkg.github.com/mpgp/mpgp/mpgpelastickibana
          docker push docker.pkg.github.com/mpgp/mpgp/mpgpelastickibana

          docker tag mpgp129/mpgpdb docker.pkg.github.com/mpgp/mpgp/mpgpdb
          docker push docker.pkg.github.com/mpgp/mpgp/mpgpdb